
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzmsxpcmmzihrhuorlmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bXN4cGNtbXppaHJodW9ybG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzc5ODYsImV4cCI6MjA2MDY1Mzk4Nn0.Qx1kJl8DMmXwBUGw8KwtWsERsWLQqd7XHolNG0fhfBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
